### ISSUE TITLE
小米平板5pro返回后会崩溃

### ISSUE THREAD

**Issue by WaterSeekingFish** [Jason-wam/Cat-Maven-2023#11]
崩溃信息:
ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

类名:androidx.recyclerview.widget.RecyclerView$Adapter

方法:createViewHolder

行数:27

类型:java.lang.IllegalStateException

时间:2023-08-08_02:08

设备名称:M2105K81AC

设备厂商:Xiaomi

系统版本:Android 13-33

CPU-ABI:arm64-v8a

versionCode:210

versionName:2.1.0.hd

全部信息:
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(Unknown Source:27)
	at androidx.recyclerview.widget.RecyclerView$Recycler.i(SourceFile:853)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.a(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:357)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:60)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23876)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23876)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23876)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23876)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(Unknown Source:32)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:166)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onFocusSearchFailed(Unknown Source:47)
	at androidx.recyclerview.widget.RecyclerView.focusSearch(Unknown Source:144)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1088)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1088)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1088)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1088)
	at android.view.View.focusSearch(View.java:13289)
	at android.view.AccessibilityInteractionController.focusSearchUiThread(AccessibilityInteractionController.java:732)
	at android.view.AccessibilityInteractionController.-$$Nest$mfocusSearchUiThread(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1670)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by Jason-wam** [comment]
具体在哪个界面，描述下操作过程
