### ISSUE TITLE
删除本地视频就崩溃

### ISSUE THREAD

**Issue by BruceWeRRa** [Jason-wam/Cat-Maven-2023#50]
崩溃信息:
Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{c253171 VFED..... ......ID 0,0-1080,2022 #102000a android:id/list}, adapter:l4.s@51fc601, layout:androidx.recyclerview.widget.LinearLayoutManager@b8d0961, context:com.jason.videocat.ui.activity.FragmentHolderActivity@f8bf9d9

类名:SourceFile

方法:assertNotInLayoutOrScroll

行数:22

类型:java.lang.IllegalStateException

时间:2024-07-01_23:11

设备名称:SM-S9010

设备厂商:samsung

系统版本:Android 14-34

CPU-ABI:arm64-v8a

versionCode:305

versionName:3.0.5.main

全部信息:
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{c253171 VFED..... ......ID 0,0-1080,2022 #102000a android:id/list}, adapter:l4.s@51fc601, layout:androidx.recyclerview.widget.LinearLayoutManager@b8d0961, context:com.jason.videocat.ui.activity.FragmentHolderActivity@f8bf9d9
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(SourceFile:22)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(SourceFile:4)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(SourceFile:1)
	at z4.l2.onCheckedChanged(SourceFile:32)
	at com.google.android.material.checkbox.MaterialCheckBox.setCheckedState(SourceFile:81)
	at com.google.android.material.checkbox.MaterialCheckBox.setChecked(Unknown Source:0)
	at z4.o2.invoke(SourceFile:108)
	at a4.h.onBindViewHolder(SourceFile:268)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(Unknown Source:40)
	at androidx.recyclerview.widget.RecyclerView$Recycler.j(SourceFile:49)
	at androidx.recyclerview.widget.RecyclerView$Recycler.k(SourceFile:1049)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.a(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:752)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:60)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:

**Comment by Jason-wam** [comment]
选择时崩溃还是删除后崩溃

**Comment by nskds** [comment]
> 选择时崩溃还是删除后崩溃

长按某一个视频选择时显示崩溃，然后是粉红色界面显示崩溃信息，删除不了视频，麻烦修一下感谢技术大大

**Comment by Jason-wam** [comment]
> > 选择时崩溃还是删除后崩溃
> 
> 长按某一个视频选择时显示崩溃，然后是粉红色界面显示崩溃信息，删除不了视频，麻烦修一下感谢技术大大

可以具体到哪个页面吗，可以的话麻烦截个图哦

**Comment by nskds** [comment]
> > > 选择时崩溃还是删除后崩溃
> > 
> > 
> > 长按某一个视频选择时显示崩溃，然后是粉红色界面显示崩溃信息，删除不了视频，麻烦修一下感谢技术大大
> 
> 可以具体到哪个页面吗，可以的话麻烦截个图哦

长按后是这样![Screenshot_2024-07-02-10-48-43-899_com walixiwa flash player](https://github.com/Jason-wam/Cat-Maven-2023/assets/174400332/3be0f811-db71-4e2d-bef0-34770c3c7016)
点右边的格子后就是粉红色界面了
![Screenshot_2024-07-02-10-48-51-099_com walixiwa flash player](https://github.com/Jason-wam/Cat-Maven-2023/assets/174400332/56f8c308-9efe-4987-8033-8fef51a1b630)

**Comment by Jason-wam** [comment]
好的等待测试

**Comment by Jason-wam** [comment]
已修复，请下载测试[资源猫2024 - 3.0.5.apk](https://xswl.lanzn.com/iCfcP23ess8j)

**Comment by BruceWeRRa** [comment]
显示分享取消 无法下载了
















在 2024-07-03 15:48:42，"面条君" ***@***.***> 写道：

已修复，请下载测试资源猫2024 - 3.0.5.apk

**Comment by Jason-wam** [comment]
> 显示分享取消 无法下载了
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 在 2024-07-03 15:48:42，"面条君" ***@***.***> 写道：
> 
> 已修复，请下载测试资源猫2024 - 3.0.5.apk
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

https://xswl.lanzn.com/iXyYW23f5xaj

**Comment by BruceWeRRa** [comment]
感谢 已解决
















在 2024-07-04 10:54:31，"面条君" ***@***.***> 写道：

Closed #50 as completed.
