### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by cshangdic** [Jason-wam/Cat-Maven-2023#55]
升到最新的3.0.7  播放任何视频时，都报outOfMemory

![device-2024-07-04-090912](https://github.com/Jason-wam/Cat-Maven-2023/assets/14158273/608cd29a-56b3-461d-bb6f-daed1db38e87)

**Comment by Jason-wam** [comment]
> 升到最新的3.0.7  播放任何视频时，都报outOfMemory
> 
> 
> ![device-2024-07-04-090912](https://github.com/Jason-wam/Cat-Maven-2023/assets/14158273/608cd29a-56b3-461d-bb6f-daed1db38e87)
> 

是缓存的视频还是直接播放的视频

**Comment by Jason-wam** [comment]
先尝试卸载重装
https://xswl.lanzn.com/iXyYW23f5xaj

**Comment by cshangdic** [comment]
在搜索中找到的资源，立即播放，然后 boom

**Comment by cshangdic** [comment]
卸载重装无用

**Comment by Jason-wam** [comment]
> 在搜索中找到的资源，立即播放，然后 boom

我这边测试没有问题，你先换回老版本吧，等这边继续排查一下，https://xswl.lanzn.com/b01a19ryd

**Comment by Jason-wam** [comment]
> 升到最新的3.0.7  播放任何视频时，都报outOfMemory
> 
> 
> ![device-2024-07-04-090912](https://github.com/Jason-wam/Cat-Maven-2023/assets/14158273/608cd29a-56b3-461d-bb6f-daed1db38e87)
> 

麻烦发一下完整的日志

**Comment by Jason-wam** [comment]
发一下手机型号+完整崩溃日志

**Comment by cshangdic** [comment]
崩溃信息:
pthread_create (1040KB stack) failed: Out of memory

类名:Thread.java

方法:nativeCreate

行数:-2

类型:java.lang.OutOfMemoryError

时间:2024-07-04_11:30

设备名称:CLT-AL00

设备厂商:HUAWEI

系统版本:Android 10-29

CPU-ABI:arm64-v8a

versionCode:307

versionName:3.0.7.main

全部信息:
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:893)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.execute(Unknown Source:21)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.start(Unknown Source:30)
	at androidx.media3.exoplayer.upstream.Loader.startLoading(Unknown Source:31)
	at androidx.media3.exoplayer.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.loadPlaylistImmediately(Unknown Source:40)
	at androidx.media3.exoplayer.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.loadPlaylistInternal(Unknown Source:56)
	at androidx.media3.exoplayer.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.loadPlaylist(Unknown Source:2)
	at androidx.media3.exoplayer.hls.playlist.DefaultHlsPlaylistTracker.onLoadCompleted(SourceFile:2)
	at androidx.media3.exoplayer.hls.playlist.DefaultHlsPlaylistTracker.onLoadCompleted(SourceFile:1)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.handleMessage(Unknown Source:131)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by cshangdic** [comment]
华为P20 pro

**Comment by Jason-wam** [comment]
> 华为P20 pro

目前其他手机还没有复现，等待排查

**Comment by Jason-wam** [comment]
麻烦留一下QQ，方便测试联系

**Comment by cshangdic** [comment]
270263735

**Comment by Jason-wam** [comment]
修改了一下，可以下载测试一下[资源猫测试版](https://xswl.lanzn.com/i8eRd23hzhrc)

这种问题好像在P20出现的比较多，试试其他手机是否出现相同的问题，解决比较困难
