### ISSUE TITLE
未响应

### ISSUE THREAD

**Issue by zwlqa** [Jason-wam/Cat-Maven-2023#8]
崩溃信息:
ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

类名:androidx.recyclerview.widget.RecyclerView$Adapter

方法:createViewHolder

行数:27

类型:java.lang.IllegalStateException

时间:2023-07-08_07:29

设备名称:23046RP50C

设备厂商:Xiaomi

系统版本:Android 13-33

CPU-ABI:arm64-v8a

versionCode:207

versionName:2.0.7.hd

全部信息:
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(Unknown Source:27)
	at androidx.recyclerview.widget.RecyclerView$Recycler.i(SourceFile:853)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.a(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:357)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:60)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23944)
	at android.view.ViewGroup.layout(ViewGroup.java:6492)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23944)
	at android.view.ViewGroup.layout(ViewGroup.java:6492)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23944)
	at android.view.ViewGroup.layout(ViewGroup.java:6492)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23944)
	at android.view.ViewGroup.layout(ViewGroup.java:6492)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(Unknown Source:32)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:166)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onFocusSearchFailed(Unknown Source:47)
	at androidx.recyclerview.widget.RecyclerView.focusSearch(Unknown Source:144)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1090)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1090)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1090)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1090)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:1090)
	at android.view.View.focusSearch(View.java:13300)
	at android.view.AccessibilityInteractionController.focusSearchUiThread(AccessibilityInteractionController.java:732)
	at android.view.AccessibilityInteractionController.-$$Nest$mfocusSearchUiThread(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1670)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by Jason-wam** [comment]
从错误日志中无法看出具体错误位置，能说一下什么地方或者什么操作报错吗

**Comment by zwlqa** [comment]
片单出现卡顿然后就闪退

**Comment by zwlqa** [comment]
片单页面出现卡顿然后就闪退

**Comment by zwlqa** [comment]
基本上没发正常使用这个劲的闪退，设备小米平板6pro
